### ISSUE TITLE
Longest common prefix search

### ISSUE THREAD

**Issue by derkan** [absolutelightning/treds#8]
What is performance  of finding longest common prefix?

**Comment by absolutelightning** [comment]
Hey @derkan 
Thanks for creating the issue. 
So by longest common prefix - do you mean the common prefix across all keys? or
Given a input string, we need to find the longest key in store being prefix of give input string?

**Comment by absolutelightning** [comment]
Hey @derkan - I have added Longest Prefix Command in https://github.com/absolutelightning/treds/pull/11
It is similar to Get but instead of exact match it returns the longest prefix match kv pair.
Time Complexity is O(k) where k is the length of search key. 
Please feel free to reopen in case you needed something else.

**Comment by derkan** [comment]
Thank you!
